import type { Metadata } from "next";
import { Geist, Inter, Poppins } from "next/font/google";
import "./globals.css";
import NavigationProvider from "./hooks/useNavigation";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // ← choisis les poids que tu veux charger
  variable: "--font-poppins", // ← pour utiliser une variable CSS
  display: "swap", // ← bonne pratique pour éviter les flashs
});
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body className={` ${poppins.variable} antialiased`}>
        <NavigationProvider>{children}</NavigationProvider>
      </body>
    </html>
  );
}
